<?php

namespace ContainerPljOeHh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDatabaseInitDataCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\DatabaseInitDataCommand' shared autowired service.
     *
     * @return \App\Command\DatabaseInitDataCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'DatabaseInitDataCommand.php';

        $container->privates['App\\Command\\DatabaseInitDataCommand'] = $instance = new \App\Command\DatabaseInitDataCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setName('database:init_data');
        $instance->setDescription('This command is used to initialize the database.');

        return $instance;
    }
}
